CREATE TABLE IF NOT EXISTS tcp_tunnels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  listen_port INT NOT NULL,
  target_host VARCHAR(255) NOT NULL,
  target_port INT NOT NULL,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tcp_tunnel_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tunnel_id INT,
  level ENUM('info','warning','error'),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);